/* istanbul ignore file */

export default [
	{
		name: "seasonId",
		type: "select",
		label: "Season ID",
		placeholder: "Select a season id...",
		icon: "id",
		value: "",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: [],
	},
	{
		name: "eventType",
		type: "select",
		label: "Event Type",
		placeholder: "Select a league...",
		icon: "calander",
		value: "Game",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: ["Game", "Promotional", "Other"],
	},
	{
		name: "team",
		type: "select",
		label: "Team",
		placeholder: "Select a team...",
		icon: "puck",
		value: "San Jose Sharks",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: ["San Jose Sharks", "San Jose Barracuda"],
	},
	{
		name: "opponent",
		type: "select",
		label: "Opponent",
		placeholder: "Search and select an opponent (if applicable)...",
		icon: "puck",
		value: "",
		errors: "",
		required: false,
		disabled: true,
		isSearchable: true,
		selectOptions: [],
	},
	{
		name: "location",
		type: "text",
		label: "Event Location",
		icon: "location",
		value: "SAP Center at San Jose",
		errors: "",
		placeholder: "Enter an event location...",
		required: true,
		disabled: true,
	},
	{
		type: "date",
		name: "eventDate",
		label: "Event Date",
		placeholder: "Select a start date and time...",
		value: null,
		errors: "",
		required: true,
		format: "MM/DD/YYYY h:mm a",
		showTime: { format: "h:mm a", use12Hours: true, minuteStep: 5 },
		style: { width: "100%" },
	},
	{
		name: "uniform",
		type: "select",
		label: "Event Attire",
		placeholder: "Select a uniform...",
		icon: "tshirt",
		value: "",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: [
			"Sharks Teal Jersey",
			"Sharks Black Jersey",
			"Sharks Jacket",
			"Barracuda Jacket",
			"Barracuda Jersey",
			"Other",
		],
	},
	{
		name: "notes",
		type: "textarea",
		label: "Event Notes",
		value: "",
		errors: "",
		placeholder: "(Optional) Include any special event notes...",
		required: false,
		disabled: true,
	},
	{
		type: "time",
		name: "callTime",
		label: "Scheduling Call Times",
		placeholder: "Select a call time...",
		tooltip:
			"WARNING - Changing any of the call times below will reset the schedule for this event.",
		value: null,
		errors: "",
		required: true,
		style: { width: "100%" },
	},
];
