version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:10.20.1
    steps:
      - run:
          name: Redeploy Application
          command: ssh -o "StrictHostKeyChecking no" -v $DROPLET_USER@$DROPLET_IP "cd /var/www/sjsiceteam.com/app; git pull origin master; yarn install; yarn build; pm2 restart 0"
