// dashboard
export const DASHBOARD_FETCH_APFORM = "DASHBOARD/FETCH_APFORM";
export const DASHBOARD_FETCH_AVAILABILITY = "DASHBOARD/FETCH_AVAILABILITY";
export const DASHBOARD_FETCH_MEMBERS_AVAILABILITY =
	"DASHBOARD/FETCH_MEMBERS_AVAILABILITY";
export const DASHBOARD_FETCH_EVENTS = "DASHBOARD/FETCH_EVENT";
export const DASHBOARD_RESET = "DASHBOARD/RESET";
export const DASHBOARD_SET_APFORM = "DASHBOARD/SET_APFORM";
export const DASHBOARD_SET_AVAILABILITY = "DASHBOARD/SET_AVAILABILITY";
export const DASHBOARD_SET_MEMBERS_AVAILABILITY =
	"DASHBOARD/SET_MEMBERS_AVAILABILITY";
export const DASHBOARD_SET_EVENTS = "DASHBOARD/SET_EVENT";
export const DASHBOARD_FETCH_EVENT_DISTRIBUTION =
	"DASHBOARD/FETCH_EVENT_DISTRIBUTION";
export const DASHBOARD_SET_EVENT_DISTRIBUTION =
	"DASHBOARD/SET_EVENT_DISTRIBUTION";

// events
export const EVENTS_CREATE = "EVENTS/CREATE";
export const EVENTS_DELETE = "EVENTS/DELETE";
export const EVENTS_DELETE_MANY = "EVENTS/DELETE_MANY";
export const EVENTS_EDIT = "EVENTS/EDIT";
export const EVENTS_FETCH = "EVENTS/FETCH";
export const EVENTS_RESET = "EVENTS/RESET";
export const EVENTS_RESEND_MAIL = "EVENTS/RESEND_MAIL";
export const EVENTS_SET = "EVENTS/SET";
export const EVENTS_SET_EDIT = "EVENTS/SET_EDIT";
export const EVENTS_SET_NEW_EVENT = "EVENTS/SET_NEW_EVENT";
export const EVENTS_UPDATE = "EVENTS/UPDATE";

export const EVENTS_FETCH_SCHEDULE_EVENTS = "EVENTS/FETCH_SCHEDULE_EVENTS";
export const EVENTS_SET_SCHEDULE_EVENTS = "EVENTS/SET_SCHEDULE_EVENTS";

export const EVENTS_SET_SCHEDULE = "EVENTS/SET_SCHEDULE";
export const EVENTS_UPDATE_SCHEDULE = "EVENTS/UPDATE_SCHEDULE";

// forms
export const FORMS_CREATE = "FORMS/CREATE";
export const FORMS_DELETE = "FORMS/DELETE";
export const FORMS_DELETE_MANY = "FORMS/DELETE_MANY";
export const FORMS_FETCH = "FORMS/FETCH";
export const FORMS_RESEND_MAIL = "FORMS/RESEND_MAIL";
export const FORMS_RESET = "FORMS/RESET";
export const FORMS_SET = "FORMS/SET";
export const FORMS_SET_EDIT = "FORMS/SET_EDIT";
export const FORMS_UPDATE = "FORMS/UPDATE";
export const FORMS_SET_AP = "FORMS/SET_AP";
export const FORMS_UPDATE_AP = "FORMS/UPDATE_AP";

// mail
export const MAIL_CONTACT_US = "MAIL/CONTACT_US";
export const MAIL_CREATE = "MAIL/CREATE";
export const MAIL_DELETE = "MAIL/DELETE";
export const MAIL_DELETE_MANY = "MAIL/DELETE_MANY";
export const MAIL_FETCH = "MAIL/FETCH";
export const MAIL_RESEND = "MAIL/RESEND";
export const MAIL_RESET = "MAIL/RESET";
export const MAIL_SET = "MAIL/SET";
export const MAIL_SET_EDIT = "MAIL/SET_EDIT";
export const MAIL_UPDATE_EDIT = "MAIL/UPDATE_EDIT";

// members
export const MEMBERS_CREATE = "MEMBERS/CREATE";
export const MEMBERS_DELETE = "MEMBERS/DELETE";
export const MEMBERS_DELETE_MANY = "MEMBERS/DELETE_MANY";
export const MEMBERS_FETCH = "MEMBERS/FETCH";
export const MEMBERS_FETCH_AVAILABILITY = "MEMBERS/FETCH_AVAILABILITY";
export const MEMBERS_FETCH_EVENTS = "MEMBERS/FETCH_EVENTS";
export const MEMBERS_FETCH_SETTINGS = "MEMBERS/FETCH_SETTINGS";
export const MEMBERS_FETCH_SETTINGS_AVAILABILITY =
	"MEMBERS/FETCH_SETTINGS_AVAILABILITY";
export const MEMBERS_FETCH_SETTINGS_EVENTS = "MEMBERS/FETCH_SETTINGS_EVENTS";
export const MEMBERS_RESEND_TOKEN = "MEMBERS/RESEND_TOKEN";
export const MEMBERS_RESET = "MEMBERS/RESET";
export const MEMBERS_REVIEW = "MEMBERS/REVIEW";
export const MEMBERS_SET = "MEMBERS/SET";
export const MEMBERS_SET_AVAILABILITY = "MEMBERS/SET_AVAILABILITY";
export const MEMBERS_SET_NAMES = "MEMBERS/SET_NAMES";
export const MEMBERS_SET_EVENTS = "MEMBERS/SET_EVENTS";
export const MEMBERS_SET_REVIEW = "MEMBERS/SET_REVIEW";
export const MEMBERS_UPDATE = "MEMBERS/UPDATE";
export const MEMBERS_UPDATE_STATUS = "MEMBERS/UPDATE_STATUS";
export const MEMBERS_UPDATE_SETTINGS = "MEMBERS/UPDATE_SETTINGS";

export const MEMBERS_DELETE_TOKEN = "MEMBERS/DELETE_TOKEN";
export const MEMBERS_RESET_TOKENS = "MEMBERS/RESET_TOKENS";
export const MEMBERS_DELETE_MANY_TOKENS = "MEMBERS/DELETE_MANY_TOKENS";
export const MEMBERS_FETCH_TOKEN = "MEMBERS/FETCH_TOKEN";
export const MEMBERS_SET_TOKEN = "MEMBERS/SET_TOKEN";
export const MEMBERS_UPDATE_TOKEN = "MEMBERS_UPDATE_TOKEN";

export const MEMBERS_FETCH_TOKENS = "MEMBERS/FETCH_TOKENS";
export const MEMBERS_SET_TOKENS = "MEMBERS/SET_TOKENS";

// server messages
export const MESSAGE_RESET = "MESSAGE/RESET";
export const MESSAGE_SET = "MESSAGE/SET";

// seasons
export const SEASONS_DELETE = "SEASONS/DELETE";
export const SEASONS_DELETE_MANY = "SEASONS/DELETE_MANY";
export const SEASONS_SET_EDIT = "SEASONS/SET_EDIT";
export const SEASONS_UPDATE_EDIT = "SEASONS/UPDATE_EDIT";
export const SEASONS_CREATE = "SEASONS/CREATE";
export const SEASONS_FETCH = "SEASONS/FETCH";
export const SEASONS_FETCH_IDS = "SEASONS/FETCH_IDS";
export const SEASONS_RESET = "SEASONS/RESET";
export const SEASONS_SET = "SEASONS/SET";
export const SEASONS_SET_IDS = "SEASONS/SET_IDS";

// teams
export const TEAMS_FETCH_NAMES = "TEAMS/FETCH_NAMES";
export const TEAMS_SET_NAMES = "TEAMS/SET_NAMES";

// user avatar
export const USER_DELETE_AVATAR = "USER/DELETE_AVATAR";
export const USER_UPDATE_AVATAR = "USER/UPDATE_AVATAR";
export const USER_SET_AVATAR = "USER/SET_AVATAR";
// user password
export const USER_PASSWORD_UPDATE = "USER/PASSWORD_UPDATE";
export const USER_PASSWORD_RESET = "USER/PASSWORD_RESET";
// ui sidebar state
export const USER_SET_SIDEBAR_STATE = "USER/SET_SIDEBAR_STATE";
// user auth
export const USER_SIGNIN = "USER/SIGNIN";
export const USER_SIGNIN_ATTEMPT = "USER/SIGNIN_ATTEMPT";
export const USER_SIGNOUT = "USER/SIGNOUT";
export const USER_SIGNOUT_SESSION = "USER/SIGNOUT_SESSION";
export const USER_SIGNUP = "USER/SIGNUP";
export const USER_UPDATE = "USER/UPDATE";
